USE sysprevnucleos_hom
GO

/*

CONVERTER UMA PROCEDURE ORACLE PARA SQL

*/

SET ANSI_NULLS ON 
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE MEPB0129_ADRIANO 
      @PSCDFUN		CHAR(3),
      @PSCDPAT		CHAR(3),
      @PSNRPLA		CHAR(2),
      @PSDTMESREF	CHAR(10),
      @PSDCUSU      VARCHAR(255),
      @PSDCERR		VARCHAR(255) OUTPUT
AS
BEGIN

		SET NOCOUNT ON

    
DECLARE			@SDTMESANT				CHAR(6),
				@STPSEXPAR				CHAR(1),
				@SNRPLA					CHAR(2),
				@SCDPAT					CHAR(3),
				@SCDLAN					CHAR(5),
				@DDTAUX					DATE,
				@DDTAUX1				DATE,
				@DDTULTDIAMESREF		DATE,
				@NCDLAN					SMALLINT,
				@NIDORI					SMALLINT,
				@NNRIDA					SMALLINT,
				@NQTPAR					SMALLINT,
				@NQTREG					SMALLINT,
				@SDCERR					VARCHAR(255);

				SET @PSDCERR = NULL;

DECLARE @C_POPULACAO CURSOR

SET @C_POPULACAO = 
SELECT	1,
		ISNULL(@PSCDPAT, '999') AS CDPAT,
		ISNULL(@PSNRPLA, '99') AS NRPLA,
		FLOOR(DATEDIFF(MONTH, P.DTNSCPAR, @DDTULTDIAMESREF) / 12.0) AS YearsDifference,
		P.TPSEXPAR,
		COUNT(1) AS ParticipantCount
FROM	PAR_HISITPAR H
JOIN	PAR_PARTICIPANTES P ON P.NRISC = H.NRISC
JOIN	PAR_PARPLA A ON H.IDPARPLA = A.IDPARPLA
WHERE	H.CDFUN = @PSCDFUN
AND		(H.CDPAT = @PSCDPAT OR @PSCDPAT IS NULL)
AND		H.NRPLA = ( SELECT	NRPLA
					FROM	PAR_PARPLA
					WHERE	CDFUN = H.CDFUN
					AND		CDPAT = H.CDPAT
					AND		NRISC = H.NRISC
					AND		DTISCPAR = (	SELECT MAX(DTISCPAR)
											FROM PAR_PARPLA
											WHERE CDFUN = H.CDFUN
												AND CDPAT = H.CDPAT
												AND NRISC = H.NRISC
										)
					AND (NRPLA = @PSNRPLA OR @PSNRPLA IS NULL)
					)
					AND H.DTINISIT = (
											SELECT MAX(DTINISIT)
											FROM PAR_HISITPAR
											WHERE CDFUN = H.CDFUN
											AND CDPAT = H.CDPAT
											AND NRISC = H.NRISC
											AND NRPLA = H.NRPLA
											AND DTINISIT <= @DDTULTDIAMESREF
											AND (
												DTFIMSIT IS NULL OR
												DTFIMSIT >= @DDTULTDIAMESREF OR
												DTSISFIM >= @DDTULTDIAMESREF
												)
											AND DTSISINI <= @DDTULTDIAMESREF
											)
					AND H.SQSIT = (
											SELECT MAX(SQSIT)
											FROM PAR_HISITPAR
											WHERE CDFUN = H.CDFUN
											AND CDPAT = H.CDPAT
											AND NRISC = H.NRISC
											AND NRPLA = H.NRPLA
											AND DTINISIT = H.DTINISIT
											AND DTINISIT <= @DDTULTDIAMESREF
											AND (
													DTFIMSIT IS NULL OR
													DTFIMSIT >= @DDTULTDIAMESREF OR
													DTSISFIM >= @DDTULTDIAMESREF
											)
											AND DTSISINI <= @DDTULTDIAMESREF
				)
AND H.CDSITPLAATU IN ('01', '04', '21', '23')
AND ISNULL(P.IDISCCTL, 'N') = 'N'
GROUP BY 
FLOOR(DATEDIFF(MONTH, P.DTNSCPAR, @DDTULTDIAMESREF) / 12.0), P.TPSEXPAR

UNION
           
SELECT
		2,
		ISNULL(@PSCDPAT, '999') AS CDPAT,
		ISNULL(@PSNRPLA, '99') AS NRPLA,
		ROUND(DATEDIFF(MONTH, X.DTNSCPAR, @DDTULTDIAMESREF) / 12.0, 0) AS YearsDifference,
		X.TPSEXPAR,
		COUNT(1) AS ParticipantCount
FROM (
		SELECT DISTINCT P.IDPAR, P.DTNSCPAR, P.TPSEXPAR
		FROM  BNF_BNFCONCEDIDOS BC,  BNF_BENEFICIOS BF,  BNF_BENEFICIARIOS BE, PAR_PARTICIPANTES P, PAR_PARPLA A
		WHERE BC.CDFUN = @PSCDFUN
		AND (BC.CDPAT = @PSCDPAT OR @PSCDPAT IS NULL)
		AND FORMAT(BC.DTCOSBNF, 'yyyyMM') <= @PSDTMESREF
		AND (BC.NRPLA = @PSNRPLA OR @PSNRPLA IS NULL)
		AND ISNULL(BC.PRPAGUNC, 0) < 100
		AND BF.TPBNF IN ('AP', 'BP')
		AND NOT EXISTS (
							SELECT 1
							FROM BNF_BENOCOR BO
							WHERE BO.CDFUN = BC.CDFUN
							AND BO.NRPCSFUN = BC.NRPCSFUN
							AND (
									BO.TPOCO = 'E' OR
									UPPER(BO.DCMOTOCO) LIKE '%FALEC%' OR
									UPPER(BO.DCMOTOCO) LIKE '%ÓBITO%' OR
									UPPER(BO.DCMOTOCO) LIKE '%OBITO%'
							)
							AND FORMAT(BO.DTSISOCO, 'yyyyMM') < @PSDTMESREF
							AND BO.DTFIMOCO IS NULL
						)
		AND NOT EXISTS (
							SELECT 1
							FROM BNF_BENOCOR BO
							WHERE BO.CDFUN = BC.CDFUN
							AND BO.NRPCSFUN = BC.NRPCSFUN
							AND BO.TPOCO = 'E'
							AND FORMAT(BO.DTSISOCO, 'yyyyMM') = @PSDTMESREF
							AND NOT EXISTS (
												SELECT 1
												FROM BNF_HIBENEFS HB
												WHERE HB.CDFUN = BO.CDFUN
												AND HB.NRPCSFUN = BO.NRPCSFUN
												AND HB.DTMESREF = @PSDTMESREF
												)
						)
		AND NOT EXISTS (
						SELECT 1
						FROM BNF_BNFCONCEDIDOS
						WHERE CDFUN = BC.CDFUN
						AND NRPCSFUNANT = BC.NRPCSFUN
						AND FORMAT(DTCOSBNF, 'yyyyMM') <= @PSDTMESREF
		)
		AND NOT EXISTS (
						SELECT 1
						FROM BNF_HISITBNF
						WHERE CDFUN = BC.CDFUN
						AND NRPCSFUN = BC.NRPCSFUN
						AND STBNF IN ('05', '08')
						AND FORMAT(AUDATULTALT, 'yyyyMM') < @PSDTMESREF
		)
AND ISNULL(P.IDISCCTL, 'N') = 'N') X
GROUP BY ROUND(DATEDIFF(MONTH, X.DTNSCPAR, @DDTULTDIAMESREF) / 12.0, 0), X.TPSEXPAR

UNION
           
SELECT
		3,
		ISNULL(@PSCDPAT, '999') AS CDPAT,
		ISNULL(@PSNRPLA, '99') AS NRPLA,
		ROUND(DATEDIFF(MONTH, X.DTNSCDPD, @DDTULTDIAMESREF) / 12.0, 0) AS YearsDifference,
		X.TPSEXDPD,
		COUNT(1) AS ParticipantCount
FROM (
		SELECT DISTINCT D.IDDEP, D.DTNSCDPD, D.TPSEXDPD
		FROM BNF_BENEFICIARIOS BE, BNF_BNFCONCEDIDOS BC, PAR_DEPENDENTES D, PAR_PARTICIPANTES P, PAR_PARPLA A
		WHERE	BE.CDFUN = @PSCDFUN
				AND (BC.CDPAT = @PSCDPAT OR @PSCDPAT IS NULL)
				AND (BC.NRPLA = @PSNRPLA OR @PSNRPLA IS NULL)
				AND BE.SQBEN > 0
				AND FORMAT(BE.DTCOSBNF, 'yyyyMM') <= @PSDTMESREF
				AND NOT EXISTS (
									SELECT 1
									FROM BNF_BENOCOR BO
									WHERE BO.CDFUN = BE.CDFUN
									AND BO.NRPCSFUN = BE.NRPCSFUN
									AND BO.SQBEN = BE.SQBEN
									AND (
											BO.TPOCO = 'E' OR
											UPPER(BO.DCMOTOCO) LIKE '%FALEC%' OR
											UPPER(BO.DCMOTOCO) LIKE '%ÓBITO%' OR
											UPPER(BO.DCMOTOCO) LIKE '%OBITO%'
									)
									AND FORMAT(BO.DTSISOCO, 'yyyyMM') < @PSDTMESREF
									AND BO.DTFIMOCO IS NULL
				)
				AND NOT EXISTS (
									SELECT 1
									FROM BNF_BENOCOR BO
									WHERE BO.CDFUN = BE.CDFUN
									AND BO.NRPCSFUN = BE.NRPCSFUN
									AND BO.SQBEN = BE.SQBEN
									AND BO.TPOCO = 'E'
									AND FORMAT(BO.DTSISOCO, 'yyyyMM') = @PSDTMESREF
									AND NOT EXISTS (
														SELECT 1
														FROM BNF_HIBENEFS HB
														WHERE HB.CDFUN = BO.CDFUN
														AND HB.NRPCSFUN = BO.NRPCSFUN
														AND HB.DTMESREF = @PSDTMESREF
									)
				)
				AND NOT EXISTS (
				SELECT 1
				FROM BNF_BNFCONCEDIDOS
				WHERE CDFUN = BC.CDFUN
				AND NRPCSFUNANT = BC.NRPCSFUN
				AND FORMAT(DTCOSBNF, 'yyyyMM') <= @PSDTMESREF
				)
				AND NOT EXISTS (
								SELECT 1
								FROM BNF_HISITBNF
								WHERE CDFUN = BC.CDFUN
								AND NRPCSFUN = BC.NRPCSFUN
								AND STBNF IN ('05', '08')
								AND FORMAT(AUDATULTALT, 'yyyyMM') < @PSDTMESREF
				)
AND ISNULL(P.IDISCCTL, 'N') = 'N') X
GROUP BY 
ROUND(DATEDIFF(MONTH, X.DTNSCDPD, @DDTULTDIAMESREF) / 12.0, 0), X.TPSEXDPD;
    
BEGIN TRY 



OPEN CURSOR_POPULACAO;

FETCH NEXT FROM CURSOR_POPULACAO INTO


SELECT * FROM BNF_BENOCOR